version: 2.1
jobs:
  build:
    working_directory: ~/UkuApp
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: test 
          command: pwd && cd app && yarn install && yarn test && cd ..
      # - store_artifacts:
      #     path: test-results.xml
      #     prefix: tests